name: Build and Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install markdown-include and markdown-it
      run: |
        npm install -g markdown-include
        npm install -g markdown-it

    - name: Generate Output
      run: |
        markdown-include -i main.md -c markdown_include.json -o output.md

    - name: Convert Markdown to HTML
      run: |
        npx markdown-it output.md -o output.html
