name: Build and Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install markdown-include
      run: |
        python -m pip install --upgrade pip
        pip install markdown-include

    - name: Generate Output
      run: |
        python -c "
        import markdown_include.include as include;
        import markdown;
        config = {'base_path': 'docs', 'encoding': 'utf-8', 'includer': {'include': {'pattern': r'\{\{(.+)\}\}'}}};
        with open('main.md', 'r', encoding='utf-8') as input_file:
          text = input_file.read();
          included_text = include.MarkdownInclude(config).convert(text);
          html = markdown.markdown(included_text);
          with open('output.md', 'w', encoding='utf-8') as output_file:
            output_file.write(html);
        "

    - name: Convert Markdown to HTML
      uses: actions/markdown-to-html@v1
      with:
        input-file: 'output.md'
        output-file: 'output.html'
