name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
  

    - name: Install dependencies
      run: npm install

    - name: Build documentation
      run: |
        npm install -g markdown-include
        markdown-include -i doc/main.md -c doc/markdown_include.json -o README.md

    - name: Commit changes
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add README.md
        git commit -m "Generate README from doc folder" || echo "No changes to commit"
        git push origin main
